apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrole-activegate.yaml
  - clusterrolebinding-activegate.yaml
  - deployment-operator.yaml
  - role-operator.yaml
  - rolebinding-operator.yaml
  - serviceaccount-activegate.yaml
  - serviceaccount-operator.yaml
  - podsecuritypolicy-activegate.yaml
  - podsecuritypolicy-operator.yaml
bases:
  - ../crds
