apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dynatrace-activegate
  namespace: dynatrace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dynatrace-activegate
subjects:
  - kind: ServiceAccount
    name: dynatrace-activegate
    namespace: dynatrace
