kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dynatrace-data-ingest
  namespace: dynatrace
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - dynatrace-data-ingest
    verbs:
      - use
