kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dynatrace-operator
  namespace: dynatrace
  labels:
    dynatrace: activegate
    operator: oneagent
subjects:
  - kind: ServiceAccount
    name: dynatrace-operator
roleRef:
  kind: Role
  name: dynatrace-operator
  apiGroup: rbac.authorization.k8s.io
