apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dynatrace-operator
  namespace: dynatrace
  labels:
    dynatrace: operator
    operator: activegate
rules:
  - apiGroups:
      - dynatrace.com
    resources:
      - dynakubes
    verbs:
      - get
      - list
      - watch
      - update
      - create
  - apiGroups:
      - dynatrace.com
    resources:
      - dynakubes/finalizers
      - dynakubes/status
    verbs:
      - update

  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - apps
    resources:
      - replicasets
      - deployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments/finalizers
    verbs:
      - update

  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - delete
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - get
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
      - create

  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - dynatrace-operator
    verbs:
      - use

  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
